[project]
name = "robotics-lab"
version = "0.1.0"
description = "A simple example project to implement the Sense-Plan-Act Hierarchical paradigm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy==2.3.4"]
